# Generated by Django 3.1.4 on 2020-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='DummyProject',
        ),
    ]
