# Generated by Django 3.1.5 on 2021-01-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0003_auto_20201210_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionerdistrict',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='housedistrict',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='senatedistrict',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='shape',
        ),
        migrations.AddField(
            model_name='commissionerdistrict',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_dashboard.project'),
        ),
        migrations.AddField(
            model_name='housedistrict',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_dashboard.project'),
        ),
        migrations.AddField(
            model_name='senatedistrict',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_dashboard.project'),
        ),
        migrations.AddField(
            model_name='zone',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_dashboard.project'),
        ),
    ]
