# Generated by Django 3.1.5 on 2021-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0004_auto_20210119_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionerdistrict',
            name='project',
        ),
        migrations.RemoveField(
            model_name='housedistrict',
            name='project',
        ),
        migrations.RemoveField(
            model_name='senatedistrict',
            name='project',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='commissioner_districts',
            field=models.ManyToManyField(blank=True, to='asset_dashboard.CommissionerDistrict'),
        ),
        migrations.AddField(
            model_name='project',
            name='house_districts',
            field=models.ManyToManyField(blank=True, to='asset_dashboard.HouseDistrict'),
        ),
        migrations.AddField(
            model_name='project',
            name='senate_districts',
            field=models.ManyToManyField(blank=True, to='asset_dashboard.SenateDistrict'),
        ),
        migrations.AddField(
            model_name='project',
            name='zones',
            field=models.ManyToManyField(blank=True, to='asset_dashboard.Zone'),
        ),
    ]
