# Generated by Django 3.1.5 on 2021-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0005_auto_20210121_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
