# Generated by Django 3.1.5 on 2021-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0006_projectcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
