# Generated by Django 3.1.5 on 2021-02-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0007_auto_20210202_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
