# Generated by Django 3.1.6 on 2021-02-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0007_auto_20210202_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionerdistrict',
            options={'verbose_name_plural': 'Commissioner Districts'},
        ),
        migrations.AlterModelOptions(
            name='housedistrict',
            options={'verbose_name_plural': 'House Districts'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name_plural': 'Project Categories'},
        ),
        migrations.AlterModelOptions(
            name='projectscore',
            options={'verbose_name_plural': 'Project Scores'},
        ),
        migrations.AlterModelOptions(
            name='senatedistrict',
            options={'verbose_name_plural': 'Senate Districts'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='project',
            name='plan',
            field=models.ManyToManyField(blank=True, to='asset_dashboard.Plan'),
        ),
    ]
