# Generated by Django 3.1.6 on 2021-02-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0010_auto_20210205_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfinances',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
