# Generated by Django 3.1.6 on 2021-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0011_auto_20210205_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_bid_quarter',
            field=models.TextField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.TextField(blank=True, choices=[('phase_1', 'Phase 1'), ('phase_2', 'Phase 2'), ('phase_3_engineering', 'Phase 3 Engineering'), ('phase_3_construction', 'Phase 3 Construction'), ('feasibility', 'Feasibility'), ('design', 'Design'), ('construction', 'Construction')], null=True),
        ),
    ]
