# Generated by Django 3.1.7 on 2021-03-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0012_auto_20210208_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leverage_resource',
        ),
        migrations.RemoveField(
            model_name='project',
            name='obligation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='phase_completion',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plan',
        ),
    ]
