# Generated by Django 3.1.7 on 2021-03-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0013_auto_20210309_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreweights',
            name='accessibility',
        ),
        migrations.RemoveField(
            model_name='scoreweights',
            name='leverage_resource',
        ),
        migrations.RemoveField(
            model_name='scoreweights',
            name='obligation_weight',
        ),
        migrations.RemoveField(
            model_name='scoreweights',
            name='phase_completion',
        ),
    ]
