# Generated by Django 3.1.7 on 2021-03-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0015_delete_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfinances',
            name='bid_quarter',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='bond_currency',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='fees_currency',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='funded',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='grant_funds',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='grant_funds_currency',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='high_priority',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='rollover',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='rollover_currency',
        ),
        migrations.RemoveField(
            model_name='projectfinances',
            name='year',
        ),
    ]
