# Generated by Django 3.1.7 on 2021-03-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0016_auto_20210309_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfinances',
            options={'verbose_name_plural': 'Project Finances'},
        ),
        migrations.AlterModelOptions(
            name='scoreweights',
            options={'verbose_name_plural': 'Score Weights'},
        ),
    ]
