# Generated by Django 3.2.9 on 2021-12-01 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0018_auto_20211124_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.holdings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseIGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.license_iga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MowAreaDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.mow_area_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MwrdFpdLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.mwrd_fpd_lease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaturePreserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.nature_preserves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.parking_entrance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingEntranceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.parking_entrance_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingEval17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.parking_eval17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.parking_lots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PicnicGroves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.picnicgroves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.poi_amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.poi_desc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.poi_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.pointsofinterest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiToTrails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.poi_to_trails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.signage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrailsAmenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trails_amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrailsDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trails_desc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrailsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trails_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrailsMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trails_maintenace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrailSubsystemLu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'quercus.trail_subsystem_lu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3435)),
            ],
            options={
                'db_table': 'quercus.zones',
                'managed': False,
            },
        ),
    ]
