# Generated by Django 3.1.7 on 2021-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0019_add_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.TextField(choices=[('unscheduled', 'Unscheduled'), ('in-progress', 'In Progress'), ('done', 'Done')], default='unscheduled'),
        ),
    ]
