# Generated by Django 3.2.9 on 2021-12-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0019_buildings_holdings_licenseiga_mowareadb_mwrdfpdlease_names_naturepreserves_parkingentrance_parkingen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='naturepreserves',
            table='"quercus"."nature_preserves"',
        ),
    ]
