# Generated by Django 3.1.7 on 2022-01-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0022_auto_20220105_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localasset',
            name='building_id',
        ),
        migrations.AddField(
            model_name='localasset',
            name='asset_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localasset',
            name='asset_model',
            field=models.CharField(default='Buildings', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='localasset',
            name='phase',
        ),
        migrations.AddField(
            model_name='localasset',
            name='phase',
            field=models.ManyToManyField(to='asset_dashboard.Phase'),
        ),
    ]
