# Generated by Django 3.1.7 on 2022-01-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0024_localasset_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localasset',
            name='phase',
        ),
        migrations.AddField(
            model_name='localasset',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset_dashboard.phase'),
            preserve_default=False,
        ),
    ]
