# Generated by Django 3.1.7 on 2022-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0025_auto_20220126_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localasset',
            name='asset_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
