# Generated by Django 3.1.7 on 2022-03-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0027_auto_20220307_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='completed',
        ),
    ]
