# Generated by Django 3.1.7 on 2022-03-23 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0028_remove_phase_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionerdistrict',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3435),
        ),
        migrations.AddField(
            model_name='housedistrict',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3435),
        ),
        migrations.AddField(
            model_name='senatedistrict',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3435),
        ),
        migrations.AddField(
            model_name='zone',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3435),
        ),
    ]
