# Generated by Django 3.1.7 on 2022-03-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0029_auto_20220323_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingstream',
            old_name='obligated_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='fundingstream',
            name='obligated_completion_date',
        ),
    ]
