# Generated by Django 3.1.7 on 2022-03-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0030_auto_20220328_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('complete', 'Complete')], default='new'),
        ),
    ]
