# Generated by Django 3.1.7 on 2022-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0032_project_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='countywide',
            field=models.BooleanField(default=False),
        ),
    ]
