# Generated by Django 3.1.7 on 2022-04-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0033_project_countywide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseZoneDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_distribution_percentage', models.FloatField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='asset_dashboard.phase')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='asset_dashboard.zone')),
            ],
        ),
    ]
