# Generated by Django 3.1.7 on 2022-04-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0035_auto_20220425_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasezonedistribution',
            old_name='zone_distribution_percentage',
            new_name='zone_distribution_proportion',
        ),
    ]
