# Generated by Django 3.1.7 on 2022-05-13 15:02

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0036_auto_20220426_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingstream',
            name='budget',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
        migrations.AlterField(
            model_name='phase',
            name='actual_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='total_estimated_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=11),
        ),
    ]
