# Generated by Django 3.1.7 on 2022-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0039_auto_20220607_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase_type',
            field=models.TextField(blank=True, choices=[('planning_feasibility', 'Planning/Feasibility'), ('preliminary_engineering', 'Preliminary Engineering'), ('design_engineering', 'Design Engineering'), ('construction', 'Construction'), ('construction_engineering', 'Construction Engineering'), ('maintenance_repair', 'Maintenance/Repair')], null=True),
        ),
    ]
