# Generated by Django 3.2.19 on 2023-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0042_auto_20230712_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
