# Generated by Django 3.2.19 on 2023-08-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0043_phase_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliophase',
            name='phase_funding_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='asset_dashboard.fundingstream'),
        ),
    ]
