# Generated by Django 3.2.19 on 2023-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0045_auto_20230817_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='funding_streams',
            field=models.ManyToManyField(related_name='phase', to='asset_dashboard.FundingStream'),
        ),
    ]
