# Generated by Django 3.2.19 on 2025-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0045_auto_20230817_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.TextField(choices=[('active', 'Active/In-Progress'), ('inactive', 'Inactive/Hold Pending Funding'), ('complete', 'Complete')], default='inactive'),
        ),
    ]
