# Generated by Django 3.2.19 on 2025-05-13 13:34

from django.db import migrations


def forwards_func(apps, schema_editor):
    Phase = apps.get_model("asset_dashboard", "Phase")
    for phase in Phase.objects.all():
        if phase.status == "ongoing":
            phase.status = "active"
            phase.save()


def backwards_func(apps, schema_editor):
    Phase = apps.get_model("asset_dashboard", "Phase")
    for phase in Phase.objects.all():
        if phase.status == "active":
            phase.status = "ongoing"
            phase.save()


class Migration(migrations.Migration):

    dependencies = [
        ("asset_dashboard", "0046_alter_phase_status"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
