# Generated by Django 3.2.19 on 2025-05-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0047_update_ongoing_phases_to_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase_type',
            field=models.TextField(blank=True, choices=[('planning_feasibility', 'Planning/Feasibility'), ('preliminary_engineering', 'Preliminary Engineering'), ('design_engineering', 'Design Engineering'), ('construction', 'Construction'), ('construction_engineering', 'Construction Engineering'), ('maintenance_repair', 'Maintenance/Repair'), ('conditions_assessment_inspection', 'Conditions Assessment/Inspection')], null=True),
        ),
    ]
