# Generated by Django 3.2.19 on 2023-09-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0047_auto_20230831_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasezonedistribution',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='asset_dashboard.phase'),
        ),
        migrations.AlterField(
            model_name='phasezonedistribution',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='asset_dashboard.zone'),
        ),
    ]
