# Generated by Django 3.2.19 on 2023-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0049_auto_20230921_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscore',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
