# Generated by Django 3.2.19 on 2023-09-21 21:14

from django.db import migrations

def save_project_scores(apps, schema_editor):
    ProjectScore = apps.get_model('asset_dashboard', 'ProjectScore')

    for score in ProjectScore.objects.all():
        score.total_score = ProjectScore.calculate_total_score(score)
        score.save()


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0050_projectscore_total_score'),
    ]

    operations = [
        migrations.RunPython(save_project_scores),
    ]
