name: CI

on:
  push:
    branches:
      - master
      - deploy
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build containers and run tests
        run: docker-compose -f docker-compose.yml -f tests/docker-compose.yml run --rm app
      - name: Run flake8
        run: docker-compose run --rm app flake8 asset_dashboard
